apiVersion: v2
name: neon-audio
description: Deploy Neon Core Audio Service

type: application
version: 0.0.1
appVersion: "1.0.1a1"

dependencies:
  - name: base-neon
    version: 0.0.1
    repository: file://../base-neon