apiVersion: v2
name: neon-skills
description: Deploy Neon Core Skills Service

type: application
version: 0.0.1
appVersion: "1.0.1a2"

dependencies:
  - name: base-neon
    version: 0.0.1
    repository: file://../base-neon