apiVersion: v2
name: neon-script-parser
description: Deploy an MQ CCL Script Parser Service

type: application
version: 0.0.1
appVersion: "1.0.1a1"

dependencies:
  - name: base-mq
    version: 0.0.3
    repository: file://../base-mq