apiVersion: v2
name: neon-script-parser
description: Deploy an MQ CCL Script Parser Service

type: application
version: 0.0.1
appVersion: "0.0.6a13"

dependencies:
  - name: base-mq
    version: 0.0.2
    repository: file://../base-mq