apiVersion: v2
name: neon-email-proxy
description: Deploy an Email Proxy Service

type: application
version: 0.0.1
appVersion: "1.0.1a2"

dependencies:
  - name: base-mq
    version: 0.0.3
    repository: file://../base-mq