apiVersion: v2
name: neon-email-proxy
description: Deploy an Email Proxy Service

type: application
version: 0.0.1
appVersion: "0.0.6a10"

dependencies:
  - name: base-mq
    version: 0.0.1
    repository: file://../base-mq