core:
  neon-messagebus:
    image: {}
  neon-speech:
    image: {}
  neon-skills:
    image: {}
  neon-audio:
    image: {}
  neon-enclosure:
    image: {}
  neon-gui:
    image: {}
  iris-gradio:
    image: {}

  domain: diana.local
  ingress:
    rules: []