apiVersion: v2
name: neon-llm-chatgpt
description: Deploy an LLM proxy for Chat GPT

type: application
version: 0.0.1
appVersion: "1.0.1a2"

dependencies:
  - name: base-mq
    version: 0.0.3
    repository: file://../base-mq