apiVersion: v2
name: neon-llm-chatgpt
description: Deploy an LLM proxy for Chat GPT

type: application
version: 0.0.1
appVersion: "0.0.6a13"

dependencies:
  - name: base-mq
    version: 0.0.2
    repository: file://../base-mq