apiVersion: v2
name: libretranslate
description: Deploy a Libretranslate Server

type: application
version: 0.0.1
appVersion: "0.0.0"

dependencies:
  - name: base-http
    version: 0.0.1
    repository: file://../base-http