apiVersion: v2
name: libretranslate
description: Deploy a Libretranslate Server

type: application
version: 0.0.1
appVersion: "1.0.1a1"

dependencies:
  - name: base-http
    version: 0.0.2
    repository: file://../base-http