apiVersion: v2
name: neon-enclosure
description: Deploy Neon Core Enclosure Service

type: application
version: 0.0.1
appVersion: "1.0.1a1"

dependencies:
  - name: base-neon
    version: 0.0.1
    repository: file://../base-neon