apiVersion: v2
name: tts-larynx
description: Deploy a Larynx TTS Server

type: application
version: 0.0.1
appVersion: "0.0.6a13"

dependencies:
  - name: base-http
    version: 0.0.2
    repository: file://../base-http