apiVersion: v2
name: neon-llm-fastchat
description: Deploy an LLM proxy for FastChat

type: application
version: 0.0.1
appVersion: "1.0.1a1"

dependencies:
  - name: base-mq
    version: 0.0.3
    repository: file://../base-mq