apiVersion: v2
name: tts-glados
description: Deploy a Glados TTS Server

type: application
version: 0.0.1
appVersion: "1.0.1a2"

dependencies:
  - name: base-http
    version: 0.0.2
    repository: file://../base-http