# Default values for tts-glados.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
subdomain: glados
domain: diana.local
servicePort: "9666"

image:
  repository: ghcr.io/neongeckocom/neon-tts-plugin-glados
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev

service:
  type: ClusterIP
  targetPort: "9666"

ingress:
  enabled: true
  className: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - paths:
        - path: /
          pathType: Prefix
          backend:
            service:
  tls:
    secretName: tls-letsencrypt-prod
