apiVersion: v2
name: neon-messagebus
description: Deploy Neon Core Messagebus

type: application
version: 0.0.1
appVersion: "1.0.1a2"

dependencies:
  - name: base-neon
    version: 0.0.1
    repository: file://../base-neon