apiVersion: v2
name: ww-snowboy
description: Deploy Snowboy Wake Word Trainer

type: application
version: 0.0.1
appVersion: "0.0.6a14"

dependencies:
  - name: base-http
    version: 0.0.2
    repository: file://../base-http