apiVersion: v2
name: neon-metrics-service
description: Deploy a Metrics Collector Service

type: application
version: 0.0.1
appVersion: "0.0.0"

dependencies:
  - name: base-mq
    version: 0.0.1
    repository: file://../base-mq