apiVersion: v2
name: neon-metrics-service
description: Deploy a Metrics Collector Service

type: application
version: 0.0.2
appVersion: "1.0.1a1"

dependencies:
  - name: base-mq
    version: 0.0.3
    repository: file://../base-mq