apiVersion: v2
name: neon-brands-service
description: Deploy an MQ Brands Service

type: application
version: 0.0.1
appVersion: "1.0.1a1"

dependencies:
  - name: base-mq
    version: 0.0.3
    repository: file://../base-mq