apiVersion: v2
name: neon-brands-service
description: Deploy an MQ Brands Service

type: application
version: 0.0.1
appVersion: "0.0.6a14"

dependencies:
  - name: base-mq
    version: 0.0.2
    repository: file://../base-mq